# Generated by Django 5.2.3 on 2025-10-25 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_payment_stripe_session_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='stripe_session_id',
            new_name='stripe_payment_intent',
        ),
    ]
