# Generated by Django 5.2.3 on 2025-10-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_stripe_session_id_payment_stripe_payment_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('stripe', 'Stripe')], default='pending', max_length=20),
        ),
    ]
