# Generated by Django 5.2.3 on 2025-11-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_payment_payment_method_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='hire_payment',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
