# Generated by Django 5.2.3 on 2025-11-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_payment_hire_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='hire_payment',
        ),
        migrations.AddField(
            model_name='payment',
            name='hire_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('released', 'Released'), ('cancelled', 'Cancelled')], default='pending', max_length=20, null=True),
        ),
    ]
