# Generated by Django 5.2.3 on 2025-12-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_payment_hire_payment_payment_hire_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='rekognition_checked',
            field=models.BooleanField(default=False, help_text='Whether artwork was checked for duplicates'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='rekognition_labels',
            field=models.JSONField(blank=True, help_text='Detected labels from Rekognition', null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='s3_image_key',
            field=models.CharField(blank=True, help_text='S3 object key for original image', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='s3_image_url',
            field=models.URLField(blank=True, help_text='S3 URL for original image', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='s3_watermarked_key',
            field=models.CharField(blank=True, help_text='S3 object key for watermarked image', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='s3_watermarked_url',
            field=models.URLField(blank=True, help_text='S3 URL for watermarked image', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='similarity_score',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Highest similarity score with existing artworks', max_digits=5),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artworks/'),
        ),
    ]
