# Generated by Django 5.2 on 2025-12-14 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_customuser_backup_codes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_2fa_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='requires_2fa_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='verification_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='verification_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PaymentVerificationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('verification_type', models.CharField(choices=[('payment_confirm', 'Payment Confirmation'), ('payment_refund', 'Payment Refund'), ('payment_release', 'Payment Release')], default='payment_confirm', max_length=20)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_sessions', to='api.payment')),
            ],
        ),
    ]
