# Generated by Django 5.2 on 2025-12-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_payment_is_2fa_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='is_2fa_verified',
            field=models.BooleanField(default=False, help_text='Whether 2FA has been verified for this payment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='requires_2fa_verification',
            field=models.BooleanField(default=False, help_text='Whether this payment requires 2FA verification'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='verification_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Number of failed verification attempts'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='verification_locked_until',
            field=models.DateTimeField(blank=True, help_text='When verification lock expires', null=True),
        ),
    ]
