# Generated by Django 5.2 on 2025-12-14 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_payment_is_2fa_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='is_2fa_verified',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='requires_2fa_verification',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='verification_attempts',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='verification_locked_until',
        ),
        migrations.DeleteModel(
            name='PaymentVerificationSession',
        ),
    ]
