# Generated by Django 5.2 on 2026-01-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_customuser_temp_2fa_secret_twofactorsetupsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='ahash',
            field=models.CharField(blank=True, help_text='Average hash for duplicate detection', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='dhash',
            field=models.CharField(blank=True, help_text='Difference hash for duplicate detection', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='duplicate_checked',
            field=models.BooleanField(default=False, help_text='Whether artwork was checked for duplicates'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='phash',
            field=models.CharField(blank=True, help_text='Perceptual hash for duplicate detection', max_length=64, null=True),
        ),
    ]
