# Generated by Django 5.2 on 2026-01-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_artwork_ahash_artwork_dhash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='ahash',
            field=models.CharField(blank=True, db_index=True, help_text='Average hash for duplicate detection', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='dhash',
            field=models.CharField(blank=True, db_index=True, help_text='Difference hash for duplicate detection', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='duplicate_checked',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether artwork was checked for duplicates'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='phash',
            field=models.CharField(blank=True, db_index=True, help_text='Perceptual hash for duplicate detection', max_length=64, null=True),
        ),
    ]
