# Generated by Django 5.2 on 2026-01-08 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_artwork_ahash_alter_artwork_dhash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='ahash',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='dhash',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='duplicate_checked',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='phash',
        ),
    ]
