# Generated by Django 5.2 on 2026-01-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_add_artwork_like_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='perceptual_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
